sudo: required
services:
    - docker

before_install:
    - docker build -t richtercamden/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run richtercamden/react-test npm test -- --coverage

after_success:
    - docker build -t richtercamden/multi-client ./client
    - docker build -t richtercamden/multi-nginx ./nginx
    - docker build -t richtercamden/multi-server ./server
    - docker build -t richtercamden/multi-worker ./worker
    - echo "$docker_passwd" | docker login -u "$docker_id" --password-stdin
    - docker push richtercamden/multi-client
    - docker push richtercamden/multi-nginx
    - docker push richtercamden/multi-server
    - docker push richtercamden/multi-worker